# Type definitions
type Artist {
  id: ID!
  startDate: Date!
  endDate: Date
  socialLinks: SocialLinks
  images: ArtistImages
  description: String!
  displayName: String!
  secondaryDisplayName: String!
  isGroup: Boolean!

  groups: [Artist]
  members: [Artist]
  releases: [Release]!
  company: Company!

  # Computed properties
  memberCount: Int!
  groupCount: Int!
}

type SocialLinks {
  id: ID!
  twitter: String
  youtube: String
  spotify: String
}

type ArtistImages {
  id: ID!
  icon: Image
  banner: Image
  cardTall: Image
  cardFlat: Image
  artist: Artist
}

type GroupMember {
  id: ID!
  memberId: ID!
  groupId: ID!
  member: Artist!
  group: Artist!

  # Computed properties
  isActive: Boolean!
}

# Inputs
input ArtistInput {
  startDate: Date
  endDate: Date
  companyId: Int
  socialLinksId: Int
  description: String
  displayName: String
  secondaryDisplayName: String
  isGroup: Boolean
  memberCount: Int
}

input ArtistImagesInput {
  icon: Image
  banner: Image
  cardTall: Image
  cardFlat: Image
}

input GroupMemberInput {
  memberId: ID
  groupId: ID
}

input SocialLinksInput {
  twitter: String
  youtube: String
  spotify: String
}
