# Type definitions
enum ReleaseStatus {
  Delayed
  Canceled
  Postponed
  Normal
  Released
}

enum ReleaseType {
  Comeback
  Repackage
  Single
  Debut
}

type Release {
  title: String!
  subtitle: String
  date: Date
  status: ReleaseStatus
  type: ReleaseType
  
  artist: Artist!
}
