version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    environment:
      TZ: America/Vancouver
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd api && npm install
            - run: |
                sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $tz | sudo tee /etc/timezone
                sudo apt-get update -y
                sudo apt-get -y install wget ca-certificates gnupg2 lsb-release
                wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
                sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
                sudo apt-get -y install postgresql postgresql-contrib
            - run: |
                sudo service postgresql start
                sudo su - postgres -c "psql -c \"CREATE ROLE kalendar WITH LOGIN CREATEDB ENCRYPTED PASSWORD '$DBPASSWORD';\""
                createdb kalendar_test
                sequelize db:migrate
            - run: cd api && npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
